### ISSUE TITLE
IAmSpeed crashes

### ISSUE THREAD

**Issue by rR0CK3Tt** [UsrLightmann/IAmSpeed#1]
When trying to do a backup, the app crashes. 

Reason: Couldn't posix_spawn: error 1

Odysseyra1n - selio, ios 14.7, iphone 8

(This happens with IAmLazy too when using the app, using IAmLazy in settings works)

**Comment by UsrLightmann** [comment]
Just saw your Reddit message. Thanks for reporting this. Looking into it.

**Comment by UsrLightmann** [comment]
Fixed in v1.0.1 (and v1.3.1 for IAmLazy) which will be up either later tonight or early tomorrow.
